// Code generated by protoc-gen-go. DO NOT EDIT.
// source: episode-publish.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishEpisodeMessage struct {
	SeriesName           string   `protobuf:"bytes,1,opt,name=series_name,json=seriesName,proto3" json:"series_name,omitempty"`
	SeasonNo             int64    `protobuf:"varint,2,opt,name=season_no,json=seasonNo,proto3" json:"season_no,omitempty"`
	EpisodeNo            int64    `protobuf:"varint,3,opt,name=episode_no,json=episodeNo,proto3" json:"episode_no,omitempty"`
	EpisodeUrl           string   `protobuf:"bytes,4,opt,name=episode_url,json=episodeUrl,proto3" json:"episode_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishEpisodeMessage) Reset()         { *m = PublishEpisodeMessage{} }
func (m *PublishEpisodeMessage) String() string { return proto.CompactTextString(m) }
func (*PublishEpisodeMessage) ProtoMessage()    {}
func (*PublishEpisodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d56ca1176d24a8a, []int{0}
}

func (m *PublishEpisodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishEpisodeMessage.Unmarshal(m, b)
}
func (m *PublishEpisodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishEpisodeMessage.Marshal(b, m, deterministic)
}
func (m *PublishEpisodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishEpisodeMessage.Merge(m, src)
}
func (m *PublishEpisodeMessage) XXX_Size() int {
	return xxx_messageInfo_PublishEpisodeMessage.Size(m)
}
func (m *PublishEpisodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishEpisodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PublishEpisodeMessage proto.InternalMessageInfo

func (m *PublishEpisodeMessage) GetSeriesName() string {
	if m != nil {
		return m.SeriesName
	}
	return ""
}

func (m *PublishEpisodeMessage) GetSeasonNo() int64 {
	if m != nil {
		return m.SeasonNo
	}
	return 0
}

func (m *PublishEpisodeMessage) GetEpisodeNo() int64 {
	if m != nil {
		return m.EpisodeNo
	}
	return 0
}

func (m *PublishEpisodeMessage) GetEpisodeUrl() string {
	if m != nil {
		return m.EpisodeUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*PublishEpisodeMessage)(nil), "proto.PublishEpisodeMessage")
}

func init() { proto.RegisterFile("episode-publish.proto", fileDescriptor_7d56ca1176d24a8a) }

var fileDescriptor_7d56ca1176d24a8a = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2d, 0xc8, 0x2c,
	0xce, 0x4f, 0x49, 0xd5, 0x2d, 0x28, 0x4d, 0xca, 0xc9, 0x2c, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x53, 0x19, 0xb9, 0x44, 0x03, 0x20, 0x12, 0xae, 0x10, 0x75,
	0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0xf2, 0x5c, 0xdc, 0xc5, 0xa9, 0x45, 0x99, 0xa9,
	0xc5, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x5c, 0x10, 0x21,
	0xbf, 0xc4, 0xdc, 0x54, 0x21, 0x69, 0x2e, 0xce, 0xe2, 0xd4, 0xc4, 0xe2, 0xfc, 0xbc, 0xf8, 0xbc,
	0x7c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x0e, 0x88, 0x80, 0x5f, 0xbe, 0x90, 0x2c, 0x17,
	0x17, 0xd4, 0x5e, 0x90, 0x2c, 0x33, 0x58, 0x96, 0x13, 0x2a, 0xe2, 0x97, 0x0f, 0x32, 0x1c, 0x26,
	0x5d, 0x5a, 0x94, 0x23, 0xc1, 0x02, 0x31, 0x1c, 0x2a, 0x14, 0x5a, 0x94, 0x93, 0xc4, 0x06, 0x76,
	0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xed, 0x3a, 0xf3, 0x68, 0xbe, 0x00, 0x00, 0x00,
}
